spring:
  application:
    name: springbootmaster

  datasource:
    url: jdbc:postgresql://my-postgres:5432/java_postgres
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8090
  error:
    include-message: always
    include-binding-errors: always

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics, env
        exclude: loggers, httptrace
  endpoint:
    health:
      show-details: when_authorized
      roles: ADMIN
info:
  app:
    name: Beginner Java Backend
    version: 0.0.1

